name: budgetwise
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none' 

# Versioning
version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.66.0
  flutter_local_notifications: ^16.1.0
  google_mobile_ads: ^4.0.0
  intl: ^0.18.1

  cupertino_icons: ^1.0.8

  # ✅ Firebase dependencies
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_analytics: ^11.3.3
  google_sign_in: ^6.2.1
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  firebase_storage: 12.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Example to include assets (uncomment and modify if needed)
  # assets:
  #   - images/
  
  # Example to include custom fonts (uncomment and modify if needed)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf

  assets:
    - assets/images/icon.png
    - assets/images/google_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
